/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studyapp;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jordan
 */
public class StudyAppGUI extends javax.swing.JFrame {
    private ArrayList<StudySession> ss;
    /**
     * Creates new form StudyAppGUI
     */
    public StudyAppGUI() {
        initComponents();
        ss = new ArrayList<>();
        studytopicLbl.setVisible(false);
        studytopicTF.setVisible(false);
        teammatesLbl.setVisible(false);
        teammatesTF.setVisible(false);
        assessmentnameLbl.setVisible(false);
        assessmentnameTF.setVisible(false);
    }
    
    public void loadFromFile(){
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            f = new File("StudySessionData.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);
            
            ss = (ArrayList<StudySession>)oStream.readObject();
            
            oStream.close();
        }catch(IOException | ClassNotFoundException e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeGrp = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        dayLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        dayTF = new javax.swing.JTextField();
        timeTF = new javax.swing.JTextField();
        durationLbl = new javax.swing.JLabel();
        modulenameLbl = new javax.swing.JLabel();
        durationTF = new javax.swing.JTextField();
        modulenameTF = new javax.swing.JTextField();
        studytopicLbl = new javax.swing.JLabel();
        studytopicTF = new javax.swing.JTextField();
        teammatesLbl = new javax.swing.JLabel();
        teammatesTF = new javax.swing.JTextField();
        assessmentnameLbl = new javax.swing.JLabel();
        assessmentnameTF = new javax.swing.JTextField();
        personalRbtn = new javax.swing.JRadioButton();
        groupRbtn = new javax.swing.JRadioButton();
        addBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setText("Study Application");

        dayLbl.setText("Day");

        timeLbl.setText("Time(e.g 12.00)");

        timeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTFActionPerformed(evt);
            }
        });

        durationLbl.setText("Duration(in minutes)");

        modulenameLbl.setText("Module Name");

        modulenameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulenameTFActionPerformed(evt);
            }
        });

        studytopicLbl.setText("Study Topic");

        teammatesLbl.setText("Team Mates");

        assessmentnameLbl.setText("Assessment Name");

        typeGrp.add(personalRbtn);
        personalRbtn.setText("Personal Study Session");
        personalRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalRbtnActionPerformed(evt);
            }
        });

        typeGrp.add(groupRbtn);
        groupRbtn.setText("Group Project Session");
        groupRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupRbtnActionPerformed(evt);
            }
        });

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        displayBtn.setText("DISPLAY");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("DELETE LAST ITEM ADDED");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(personalRbtn)
                        .addComponent(dayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(durationLbl)
                        .addComponent(modulenameLbl)
                        .addComponent(studytopicLbl)
                        .addComponent(teammatesLbl)
                        .addComponent(assessmentnameLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(timeLbl)
                        .addGap(63, 63, 63)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(titleLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modulenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studytopicTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teammatesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assessmentnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deleteBtn)
                            .addComponent(groupRbtn))
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayBtn)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addBtn)
                                .addComponent(saveBtn)))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLbl)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personalRbtn)
                    .addComponent(groupRbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayLbl))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeLbl)
                            .addComponent(timeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addBtn))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durationLbl)
                            .addComponent(durationTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modulenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modulenameLbl))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studytopicLbl)
                            .addComponent(studytopicTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayBtn))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teammatesLbl)
                            .addComponent(teammatesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assessmentnameLbl)
                            .addComponent(assessmentnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBtn)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTFActionPerformed

    private void modulenameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulenameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modulenameTFActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if (personalRbtn.isSelected()) {
            PersonalSession p = new PersonalSession();
            
            String day = dayTF.getText();
            double time = Double.parseDouble(timeTF.getText());
            int duration = Integer.parseInt(durationTF.getText());
            String modulename = modulenameTF.getText();
            String studytopic = studytopicTF.getText();

            p.setDay(day);
            p.setTime(time);
            p.setDuration(duration);
            p.setModulename(modulename);
            p.setStudytopic(studytopic);

            ss.add(p);
        } else if (groupRbtn.isSelected()) {
            GroupSession g = new GroupSession();

            String day = dayTF.getText();
            double time = Double.parseDouble(timeTF.getText());
            int duration = Integer.parseInt(durationTF.getText());
            String modulename = modulenameTF.getText();
            String teammates = teammatesTF.getText();
            String assessmentname = assessmentnameTF.getText();

            g.setDay(day);
            g.setTime(time);
            g.setDuration(duration);
            g.setModulename(modulename);
            g.setTeammates(teammates);
            g.setAssessmentname(assessmentname);
            
            ss.add(g);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a list to add your entry to");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        try {
            File f;
            FileOutputStream fStream;
            ObjectOutputStream oStream;

            f = new File("StudySessionOutput.dat");
            fStream = new FileOutputStream(f);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(ss);
            oStream.close();
        } catch (IOException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            f = new File("StudySessionOutput.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);

            ss = (ArrayList<StudySession>) oStream.readObject();
            oStream.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e);
        }
        for (StudySession x : ss) {
            JOptionPane.showMessageDialog(null, x.getDeatils());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        File f;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try {
            f = new File("StudySessionOutput.dat");
            fStream = new FileInputStream(f);
            oStream = new ObjectInputStream(fStream);

            ss = (ArrayList<StudySession>) oStream.readObject();
            oStream.close();
        } catch (IOException | ClassNotFoundException e) {
            System.out.println(e);
        }
        StudySession s = ss.remove(ss.size()-1);
        JOptionPane.showMessageDialog(null, s.getDeatils() + "\n WILL BE DELETED ");
        JOptionPane.showMessageDialog(null, " Click save to save changes to the file ");
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void personalRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalRbtnActionPerformed
        // TODO add your handling code here:
        studytopicLbl.setVisible(true);
        studytopicTF.setVisible(true);
        teammatesLbl.setVisible(false);
        teammatesTF.setVisible(false);
        assessmentnameLbl.setVisible(false);
        assessmentnameTF.setVisible(false);
    }//GEN-LAST:event_personalRbtnActionPerformed

    private void groupRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupRbtnActionPerformed
        // TODO add your handling code here:
        studytopicLbl.setVisible(false);
        studytopicTF.setVisible(false);
        teammatesLbl.setVisible(true);
        teammatesTF.setVisible(true);
        assessmentnameLbl.setVisible(true);
        assessmentnameTF.setVisible(true);
    }//GEN-LAST:event_groupRbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudyAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudyAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudyAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudyAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudyAppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel assessmentnameLbl;
    private javax.swing.JTextField assessmentnameTF;
    private javax.swing.JLabel dayLbl;
    private javax.swing.JTextField dayTF;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel durationLbl;
    private javax.swing.JTextField durationTF;
    private javax.swing.JRadioButton groupRbtn;
    private javax.swing.JLabel modulenameLbl;
    private javax.swing.JTextField modulenameTF;
    private javax.swing.JRadioButton personalRbtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel studytopicLbl;
    private javax.swing.JTextField studytopicTF;
    private javax.swing.JLabel teammatesLbl;
    private javax.swing.JTextField teammatesTF;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JTextField timeTF;
    private javax.swing.JLabel titleLbl;
    private javax.swing.ButtonGroup typeGrp;
    // End of variables declaration//GEN-END:variables
}
